FROM ft-rails:on-build

EXPOSE 3000
CMD [ "rails" , "s", "-b", "0.0.0.0", "-p", "3000"]


# run the command of the test dockerfile in the test folder
# docker build -t ex02 .
# docker run -p 3000:3000 ex02
